# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [13]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
# Dimension (number of axes)
print("Number of axes (dimension):", A.ndim)

# Shape
print("Shape (rows, columns):", A.shape)

# Size (total number of elements)
print("Total number of elements:", A.size)

# Datatype
print("Data type of elements:", A.dtype)

Number of axes (dimension): 2
Shape (rows, columns): (3, 5)
Total number of elements: 15
Data type of elements: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [17]:
subtrection = B - C
print (subtrection)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [24]:
multiplication = B * C
print ("multiplication", multiplication)

multiplication [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [26]:
matrix_multiplication = B @ C
print (matrix_multiplication)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:

B = np.arange(1, 10).reshape(3, 3)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
#1
B = np.arange(1, 10).reshape(3, 3)
print("\nExponentiate each element:")
print(B)

#2
min_value = np.min(B) 
print ("\nMininum value in the whole matrix:", min_value)

#3
min_value_row = np.min(B, axis=1)
print("\nMinimum value in each row:", min_value_row)

#4
min_value_col = np.min(B, axis=0)
print("\nMinimum value in each column:", min_value_col)

#5 
min_index  = np.argmin(B)
print("\nIndex of the minimum value in the whole matrix:", min_index)

#6
min_index_row = [np.argmin (row) for row in B]
print("Index of the minimum value in each row:", min_index_row)

#7
sum_all = np.sum(B)
print("\nSum of all elements:", sum_all) 

#8
mean_col = np.mean(B, axis=0)
print ("\nMean of each column", mean_col)

#9 
median_col = np.median(B, axis=0)
print ("\nMedian of each column", median_col)


Exponentiate each element:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mininum value in the whole matrix: 1

Minimum value in each row: [1 4 7]

Minimum value in each column: [1 2 3]

Index of the minimum value in the whole matrix: 0
Index of the minimum value in each row: [np.int64(0), np.int64(0), np.int64(0)]

Sum of all elements: 45

Mean of each column [4. 5. 6.]

Median of each column [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [41]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [42]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# Om du anger färre index än antalet dimensioner i en matris, så väljs allt från de dimensioner som du inte har specificerat. 
# I exemplet A[1] innebär det att du bara anger ett index för raden, och då får du hela den raden, alltså [6, 7, 8, 9, 10].

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [5]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [10]:
for element in np.nditer(A):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [11]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
a = np.arange(30) #  Skapar en array a med 30 heltal, från 0 till 29.
b = a.reshape((2, 3, -1)) 
#Arrayen b har nu tre axlar
#Axel 0: Representerar de två "blocken" i arrayen.
#Axel 1: Representerar de tre raderna i varje block.
#Axel 2: Representerar de fem elementen (kolumnerna) i varje rad.
print(a)
print()

print(b)

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


Vad som händer: Matrisen m1 (2x2) adderas med vektorn m2 (1x2). Eftersom m2 har samma antal kolumner som m1, upprepas (broadcastas) m2 för varje rad i m1. 
Resultat: Varje element i m2 läggs till motsvarande kolumner i varje rad i m1.

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

 En skalär (1) adderas till alla element i vektorn v1. Broadcasting gör att 1 upprepas för varje element i vektorn.

Resultat: Alla element i v1 ökas med 1.

In [6]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


Matrisen A (2x2) adderas med vektorn b (1x2). Broadcasting gör att vektorn b upprepas för varje rad i matrisen A.

Resultat: Varje element i vektorn b läggs till motsvarande kolumner i varje rad i A.


In [14]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [18]:
def add_mult_matrices(mat1, mat2, operation):
   
    if not (isinstance(mat1, np.ndarray) and isinstance(mat2, np.ndarray)):
        return "Error: Both inputs must be of type numpy.ndarray."
    
    # Kontrollera att operationen är korrekt
    if operation not in ['add', 'multiply']:
        return "Error: Operation must be 'add' or 'multiply'."
    
    # Utför addition
    if operation == 'add':
        if mat1.shape != mat2.shape:
            return "Error: Matrices must have the same dimensions for addition."
        return mat1 + mat2
    
    # Utför multiplikation
    elif operation == 'multiply':
        if mat1.shape[1] != mat2.shape[0]:
            return "Error: Matrices are not conformable for multiplication."
        return mat1 @ mat2  # Använder @-operatorn för matrisprodukt

In [19]:
# Testa addition
add_result = add_mult_matrices(A, B, 'add')
print("Addition Result:\n", add_result)

# Testa multiplikation
mult_result = add_mult_matrices(A, B, 'multiply')
print("Multiplication Result:\n", mult_result)

# Testa med felaktig operation
error_result = add_mult_matrices(A, B, 'divide')
print("\nInvalid Operation Test:\n", error_result)

Addition Result:
 Error: Matrices must have the same dimensions for addition.
Multiplication Result:
 Error: Matrices are not conformable for multiplication.

Invalid Operation Test:
 Error: Operation must be 'add' or 'multiply'.


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [18]:
#(a) Vilken dimension har vektorn x?
x = np.array([4, 3])

#(b) Beräkna 5x.
dimension_x = x.shape
print(f"(a) Dimensionen av vektorn x: {dimension_x}")

#(c) Beräkna 3x.
result_b = 5 * x
print(f"(b) 5x: {result_b}")

#(d) Beräkna 5x + 3x.
result_d = 5 * x + 3 * x
print(f"(d) 5x + 3x: {result_d}")

#(e) Beräkna 8x.
result_e = 8 * x
print(f"(e) 8x: {result_e}")

#(f) Ber¨akna 4x − x.
result_f = 4 * x - x
print(f"(f) 4x - x: {result_f}")


#(g) Beräkna x^T, vilken blir den nya dimensionen efter att transponeringen utförts?
x_T = x.reshape(1, 2)  
print("x^T:", x_T)
print("Dimensionen efter transponering:", x_T.shape)

#(h) Är x + x^T definierat?
try:
    result = x + x_T
except ValueError as e:
    print("Addition är inte definierad:", e)
#(i) Beräkna ∥x∥.
norm_x = np.linalg.norm(x)
print("Normen av x är:", norm_x)

print ('uppgift 10.1.2 ')
print ('a) Vektorn v har fyra element, så dess dimension är 4. Det är en 4-dimensionell kolumnvektor.')

v = np.array([3, 7, 0, 11])

# (b) Beräkna 2v
two_v = 2 * v
print("b) 2v =", two_v)

# (c) Beräkna 5v + 2v
five_v = 5 * v
result_c = five_v + (2 * v)
print("c) 5v + 2v =", result_c)

# (d) Beräkna 4v - 2v
four_v = 4 * v
result_d = four_v - (2 * v)
print("d) 4v - 2v =", result_d)

# (e) Beräkna v^T (transponera vektorn)
v_transposed = v.T
print("v^T =", v_transposed)
print("Ny dimension =", v_transposed.shape)

# (f) Beräkna ||v|| (vektorns norm)
norm_v = np.linalg.norm(v)
print("f) ||v|| =", norm_v)

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) Beräkna ||v1||
norm_v1 = np.linalg.norm(v1)
print("a) ||v1|| =", norm_v1)

# (b) Beräkna ||v1 - v2||
diff_v1_v2 = v1 - v2
norm_diff_v1_v2 = np.linalg.norm(diff_v1_v2)
print("b) ||v1 - v2|| =", norm_diff_v1_v2)



(a) Dimensionen av vektorn x: (2,)
(b) 5x: [20 15]
(d) 5x + 3x: [32 24]
(e) 8x: [32 24]
(f) 4x - x: [12  9]
x^T: [[4 3]]
Dimensionen efter transponering: (1, 2)
Normen av x är: 5.0
uppgift 10.1.2 
a) Vektorn v har fyra element, så dess dimension är 4. Det är en 4-dimensionell kolumnvektor.
b) 2v = [ 6 14  0 22]
c) 5v + 2v = [21 49  0 77]
d) 4v - 2v = [ 6 14  0 22]
v^T = [ 3  7  0 11]
Ny dimension = (4,)
f) ||v|| = 13.379088160259652
a) ||v1|| = 7.14142842854285
b) ||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [19]:
A = np.array([[3, 2, 4],
              [2, 3, 8],
              [4, 1, 3],
              [7, 1, 5]])

b = np.array([7, 4, 11, 9])

# Lös ekvationssystemet
x = np.linalg.lstsq(A, b, rcond=None)[0]

# Verifiera genom att beräkna A * x och kontrollera att det är lika med b
Ax = np.dot(A, x)

# Skriv ut lösningen och verifiering
print("Lösningen x =", x)
print("Verifiering A * x =", Ax)
print("Förväntad b =", b)

Lösningen x = [ 2.13691417  4.83412322 -1.89152185]
Verifiering A * x = [ 8.51290153  3.64402317  7.70721432 10.33491311]
Förväntad b = [ 7  4 11  9]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [7]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [8]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [9]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
#För att kontrollera om v1 och v2 är en view eller en kopia kan vi använda .base:

#Om .base är None är det en kopia (original). som V1
#Om .base pekar på en annan array är det en view. som V2
